version: '3'
services:
  pypi:
    image: evi1/pypiserver:1.2.5
    volumes:
      - /home/evi1/pypi/packages:/data/packages
      - /home/evi1/pypi/logs:/data/logs
      - /home/evi1/pypi/conf:/data/conf
      # - /home/evi1/pypi/.htpasswd:/data/.htpasswd
    container_name: pypi
    ports:
      - 8888:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    # command: -P /data/.htpasswd -a update,download,list /data/packages
    # command: -v --log-file=/data/pypiserver.log --log-req-frmt '%s' --log-res-frmt '%s'  --log-err-frmt '%s' -P . -a . /data/packages 
    command: -v --log-file=/data/logs/pypiserver.log -P . -a . /data/packages 
    # command: -v /data/packages 
